# Generated by Django 3.2 on 2021-05-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
