# Generated by Django 3.2 on 2021-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
