# Generated by Django 3.2 on 2021-04-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_remove_cartitem_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='title',
        ),
    ]
