# Generated by Django 3.2 on 2021-04-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_auto_20210429_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
