# Generated by Django 3.2 on 2021-05-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_auto_20210513_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='completely_ordered',
        ),
    ]
