# Generated by Django 3.2 on 2021-05-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0016_remove_cartitem_completely_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
    ]
